name: Docker Image Build and Push

on:
  push:
    branches:
      - main  # Khi có commit lên nhánh main, workflow này sẽ chạy
  pull_request:
    branches:
      - main  # Khi có pull request vào nhánh main, workflow này cũng sẽ chạy

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    # Check out mã nguồn
    - name: Checkout code
      uses: actions/checkout@v4

    # Đăng nhập vào Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build và Push image cho backend
    - name: Build and push backend image
      run: |
        docker build -t daviseraaa/ecommerce-server-backend:latest .
        docker push daviseraaa/ecommerce-server-backend:latest

    # Build và Push image cho nginx
    - name: Build and push nginx image
      run: |
        docker build -t daviseraaa/ecommerce-server-nginx:latest ./nginx
        docker push daviseraaa/ecommerce-server-nginx:latest
